language: ruby
script: bundle exec rake
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - rbx
  - jruby-18mode
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: ruby-head
